### ISSUE TITLE
Missing Database Script

### ISSUE THREAD

**Issue by jasrei** [Dartanlla/OWS#117]
The directiosn say to run the scripts from your version to the latest version.  However, when I execute the statement SELECT * FROM OWSVersion I get the version 20210203, but the old script in the Databases folder is for version 20210829. There is no script to upgrade from 20210203.  This is a fresh clone of the repo.

**Comment by Dartanlla** [comment]
Good catch.  The file was just named wrong.  Commit [0dba181](https://github.com/Dartanlla/OWS/commit/0dba181f47a70f37d4517a660650fedc3874a105) fixes the issue.  I renamed the first file from date to 20210203.
