### ISSUE TITLE
After restarting OWS Error on Loading into game "OnTravelToLastZoneServerResponseReceived"

### ISSUE THREAD

**Issue by RastyBasic** [Dartanlla/OWS#124]
Everything looks ok but when I try to log into the game after character selection this error appears.
I tried rebuilding the docker image with no success.

OWS: Error: OnTravelToLastZoneServerResponseReceived Server returned no data!

Every help is welcome!

**Comment by SloppyShovel** [comment]
Hi @RastyBasic 

This is not an issue but rather a misconfiguration.

Please join the official Open World Server Discord in case you are still stuck with this, so we can help you troubleshoot the issue.

Official Open World Server Discord: https://discord.gg/qZ76Cmxcgp

**Comment by SloppyShovel** [comment]
@Dartanlla Good to close.
