### ISSUE TITLE
Missing sources? 

### ISSUE THREAD

**Issue by Grogdunn** [Dartanlla/OWS#20]
On website pointing this repository http://www.sabredartstudios.com/ in FAQ section there is that sentence

> How can I build my game with this system?
> 
> All you do is inherit your Game Mode from my OWSGameMode base class, your Character from my OWSCharacter (or OWSCharacterWithAbilities) base class, and your Player Controller from my OWSPlayerController base class. All of the functionality above is now available for you to use.

But I cannot find OWS* unreal base class. Where I can find these sources?

Thanks

**Comment by Dartanlla** [comment]
Hi Grogdunn,

If you are looking to get started with OWS, you will want to create an account here:

http://www.sabredartstudios.com/Marketing/FreeTrial

Then download the OWS Starter Project here:

http://rpgwebapi.sabredartstudios.com/Docs/Install

This GitHub repo is still a work in process, so you should not be using it yet.  Hopefully soon.

Thanks!
Dart
