### ISSUE TITLE
Is OWS OSx Compatible

### ISSUE THREAD

**Issue by wflieller** [Dartanlla/OWS#37]
Is this available for Mac OS x?

**Comment by CanisHelix** [comment]
Are you referring to the UE4/UE5 Plugin or OWS itself?

The plugin is not restricted and should be compatible.
OWS itself is available as per the instructions https://github.com/Dartanlla/OWS/blob/main/DOCKER.md#macos

I hope this helps.

**Comment by Dartanlla** [comment]
@wflieller OWS 2 is compatible with Mac OS X.  While I have not used it on a Mac, others in the OWS Discord have and they wrote the instructions for Mac OS that are on GitHub.  If you run into any issues, you can get help here:  https://discord.gg/qZ76Cmxcgp
