### ISSUE TITLE
MySQL update script delim error / fix

### ISSUE THREAD

**Issue by MATTG-ZEROFILL** [Dartanlla/OWS#63]
To create/update stored procedures in MySQL, it's important to treat the entire block as one statement. The current MySQL update scripts throw an error because there's no custom Delimiter statement.

see https://stackoverflow.com/questions/25885054/cant-create-basic-stored-proc-on-mariadb

I was able to resolve the issue by adding this statement BEFORE the stored procedure alteration:

`DELIMITER //`

and adding the following statement AFTER the 'END' statement:

`//
DELIMITER ;`

**Comment by MATTG-ZEROFILL** [comment]
`UPDATE OWSVersion SET OWSDBVersion='20220424' WHERE OWSDBVersion IS NOT NULL;

SELECT OWSDBVersion FROM OWSVersion;

ALTER TABLE WorldServers
ADD ZoneServerGUID CHAR(36) NULL;

DELIMITER //

CREATE OR REPLACE PROCEDURE AddOrUpdateWorldServer(_CustomerGUID CHAR(36),
                                                   _ZoneServerGUID CHAR(36),
                                                   _ServerIP VARCHAR(50),
                                                   _MaxNumberOfInstances INT,
                                                   _InternalServerIP VARCHAR(50),
                                                   _StartingMapInstancePort INT
)
BEGIN
    DECLARE _WorldServerID INT;

    SELECT WS.WorldServerID
    INTO _WorldServerID
    FROM WorldServers WS
    WHERE WS.CustomerGUID = _CustomerGUID
      AND WS.ZoneServerGUID = _ZoneServerGUID;

    IF (_WorldServerID > 0) THEN
        UPDATE WorldServers WS
        SET MaxNumberOfInstances    = _MaxNumberOfInstances,
            Port                    = 8081,
            ServerStatus            = 0,
            InternalServerIP        = _InternalServerIP,
            StartingMapInstancePort = _StartingMapInstancePort,
            ZoneServerGUID          = _ZoneServerGUID
        WHERE CustomerGUID = _CustomerGUID
          AND WS.WorldServerID = _WorldServerID
          AND WS.ZoneServerGUID = _ZoneServerGUID;
    ELSE
        INSERT INTO WorldServers (CustomerGUID, ServerIP, MaxNumberOfInstances, Port, ServerStatus, InternalServerIP,
                                  StartingMapInstancePort, ZoneServerGUID)
        VALUES (_CustomerGUID, _ServerIP, _MaxNumberOfInstances, 8081, 0, _InternalServerIP, _StartingMapInstancePort,
                _ZoneServerGUID);
    END IF;
END;

//
DELIMITER ;`

**Comment by CanisHelix** [comment]
Thanks for the report, please feel free to submit a PR and we can merge it.

Out of interest, are you using the supplied MariaDB instance or external? If external, what version? Also what MySQL/MariaDB client would be handy to know.

I've not had any other reports after multiple users have upgraded, and MariaDB 10.5 via DataGrip 2022.2.0+ has not given any warnings/errors or issues about the update scripts.

**Comment by mattgangwer** [comment]
Using a custom maria dB docker container, 10.8.3, so this issue may not exist with the latest build. Feel free to disregard and close the issue if you're not hearing about it elsewhere.  It will at least be documented in the event someone else runs into the problem.

**Comment by MATTG-ZEROFILL** [comment]
Using a custom maria dB docker container, 10.8.3, so this issue may not exist with the latest build. Feel free to disregard and close the issue if you're not hearing about it elsewhere. It will at least be documented in the event someone else runs into the problem.

**Comment by CanisHelix** [comment]
@MATTG-ZEROFILL I tested the suggestions on 10.5 and it doesn't break anything, as such I've created a PR to add the suggestions.

FYI: Work is in progress to completely remove Stored Procedures/Functions in the future and move all 'logic' over to C#.

**Comment by MATTG-ZEROFILL** [comment]
Appreciate the reply... I use entity framework with a C# API at my day job, so I have been looking at your project for tips w/my hobby (working on an mmo-lite with a fried that worked on everquest)
